#
# Configuration file for tracking using sliding
# 

dynamics:
    xLenght: 0.07 #  [meter]
    yLenght: 0.12 #  [meter]
    pusherRadious: 0.01 #  [meter]
    pusherFricCoef: 0.2
    pusherForceLim:  0.3
    pusherAngleVelLim: 2.0
    Kz_max: 1.0
    Kz_min: 1.0

TO:
    contactMode: 'sliding_mi'  # 'sticking', 'sliding_cc', 'sliding_cc_slack', or 'sliding_mi'
    solverName: 'gurobi'  # 'ipopt', 'snopt', 'gurobi', 'qpoases', 'knitro'
    W_x: [1.0, 1.0, 0.01, 0.001]  # diagonal state weights
    W_u: [0.01, 0.01, 0., 0.]  # diagonal control weights
    K_goal: 10
    X_goal: null
    linDynFlag: True
    codeGenFlag: False
    noPrintingFlag: True
    phases: null
    numObs: 0
